language: node_js
node_js:
  - "4"
  - "5"
  - "6"
script:
  - npm run check:src
  - npm run build
  # - npm run check:examples
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.npm
  - examples/ReactSimple/node_modules
  - examples/RxSimple/node_modules
after_success: npm run test:cov
